import { Book, Borrowed, Borrower } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Selection from "../components/Selection";
import MainNavbar from "../components/MainNavbar";
import MainFooter from "../components/MainFooter";
import { trpc } from "../utils/trpc";

const pageOptions = [
  {
    heading: "Books",
    content:
      "Click here to see the available books, their availability duration and the amount.",
    route: "/books",
    srcs: "/books.png",
  },
  {
    heading: "Users",
    content: "Click here to see the borrowers, their contact and the details.",
    route: "/borrower",
    srcs: "/students.png",
  },
];

const Home: NextPage = () => {
  const [borrowedData, setBorrowedData] = useState<
    (Borrowed & { book: Book; borrower: Borrower })[]
  >([]);
  trpc.useQuery(["book.getBorrowData"], {
    onSuccess(borrower) {
      setBorrowedData(borrower);
    },
  });

  return (
    <>
      <Head>
        <title>Library</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div style={{ backgroundColor: "#f2f0ee" }}>
          <MainNavbar />
          <div
            className="mt-20 flex h-80 flex-col items-center"
            style={{ backgroundColor: "#f2f0ee" }}
          >
            <div className="flex content-center">
              <h1 className="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl">
                <span className="bg-gradient-to-r from-red-500 to-red-400 bg-clip-text text-transparent">
                  Fuxam Library
                </span>{" "}
                Management System.
              </h1>
            </div>
            <div className="flex h-screen justify-center text-center">
              <p className="text-center text-lg font-normal text-gray-500 dark:text-gray-400 lg:text-xl">
                Here at Fuxam we focus on lenting books to the students for
                certain period of time.
              </p>
            </div>
          </div>
        </div>

        <div
          style={{
            display: "flex",
            flexDirection: "row",
            marginTop: "80px",
            marginBottom: "80px",
            justifyContent: "center",
          }}
          className="space-y-6"
        >
          {pageOptions.map((pageOption, idx) => (
            <Selection {...pageOption} key={idx} />
          ))}
        </div>
        <div className="relative mb-10 flex justify-center overflow-x-auto">
          <table className="text-left text-sm text-gray-500 dark:text-gray-400">
            <thead className="bg-gray-50 text-xs uppercase text-gray-700 dark:bg-gray-700 dark:text-gray-400">
              <tr>
                <th scope="col" className="px-6 py-3">
                  Book Name
                </th>
                <th scope="col" className="px-6 py-3">
                  Lend To
                </th>
                <th scope="col" className="px-6 py-3">
                  Borrowed From
                </th>
                <th scope="col" className="px-6 py-3">
                  Borrowed Till
                </th>
              </tr>
            </thead>
            {borrowedData.map(
              (
                {
                  book: { name: bookName },
                  borrower: { name: borrowerName },
                  borrowedFrom,
                  borrowedTill,
                },
                idx
              ) => (
                <tbody key={idx + bookName + borrowerName}>
                  <tr
                    key={idx}
                    className="border-b bg-white dark:border-gray-700 dark:bg-gray-800"
                  >
                    <td key={bookName + idx} className="px-6 py-4">
                      {bookName}
                    </td>
                    <td key={borrowerName + idx} className="px-6 py-4">
                      {borrowerName}
                    </td>
                    <td key={idx} className="px-6 py-4">
                      {borrowedFrom.toLocaleDateString("en-US")}
                    </td>
                    <td className="px-6 py-4">
                      {borrowedTill.toLocaleDateString("en-US")}
                    </td>
                  </tr>
                </tbody>
              )
            )}
          </table>
        </div>
        <MainFooter />
      </main>
    </>
  );
};

export default Home;
